# -*- restclient -*-

# Create user
POST http://10.0.0.117:8000/signup
Content-Type: application/json

{
        "name":"test",
        "email":"bruh@uw.edu",
        "password":"test"
}
#
POST http://10.0.0.117:8000/login
Content-Type: application/json

{
        "username":"test",
        "password":"test"
}
#
POST http://10.0.0.117:8000/logout
Content-Type: application/json

# Create user
POST http://10.0.0.117:8000/signup
Content-Type: application/json

{
        "name":"sis",
        "email":"yo",
        "password":"sispassword"
}

#
GET http://10.0.0.117:8000/users

#
GET http://10.0.0.117:8000/users/get/name/bro

#
GET http://10.0.0.117:8000/users/get/email/yo
