// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Date } from "./Date";
import type { WidgetType } from "./WidgetType";

export interface Widget { user: string, widget_type: WidgetType, entries: Array<[Date, number]>, }