name: Backend Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        working-directory: ./backend
        with:
          command: check

      - name: Run tests
        uses: actions-rs/cargo@v1
        working-directory: ./backend
        with:
          command: test
